Add clarification to Step 1 by describing how to check if you're in the VM
railsbridge-boston/docs-hardfork pull request #92
Opened 2017-08-29 19:43 UTC by SherrySeibel

I was reading some notes I took during the last RailsBridge re common questions. I updated the curriculum to expand on how to tell if you're in IRB/the VM.

2017-08-30 00:40 UTC, edwardloveall requested changes
Thanks for taking the time to do this.

2017-08-30 00:40 UTC, edwardloveall commented on sites/en/intro-to-rails/creating_a_rails_application.step
> +    Make sure you have exited irb. If you haven't, your prompt will be `irb(main):001:0>`. Exit by typing `exit`.
I think better wording would be "screen will say" instead of "prompt will be"?

2017-08-30 00:40 UTC, edwardloveall commented on sites/en/intro-to-rails/creating_a_rails_application.step
> +    Make sure you have exited irb. If you haven't, your prompt will be `irb(main):001:0>`. Exit by typing `exit`.
Instead of saying exit twice, it would be better to tell them the effect of the change:

> Leave IRB and return to the virtual machine by typing `exit`.

Or something like that.

2017-08-30 00:40 UTC, edwardloveall commented on sites/en/intro-to-rails/creating_a_rails_application.step
> +    * Enter the virtual machine by typing `vagrant ssh`
I think this could be cut down to the first and last bullet points. It'll keep it quick and let students get into the curriculum faster. Plus, as you noted, there are TAs to help 😄

2017-09-01 14:26 UTC, mxie commented on sites/en/intro-to-rails/creating_a_rails_application.step
> +    * Enter the virtual machine by typing `vagrant ssh`
I agree with this!

2017-09-01 16:13 UTC, edwardloveall approved these changes

2017-09-06 17:43 UTC, merged